### ISSUE TITLE
Feature request: thread-unsafe counterbox

### ISSUE THREAD

**Issue by vitalyisaev2** [orian/counters#3]
Thanks for a good library! I just would like to notice that it would be nice to have thread unsafe version of library (without embedded mutex), because some users won't use this object from different goroutines, therefore no need for synchronization overhead.

**Comment by orian** [comment]
It's pretty trivial to write it and in fact the early version didn't have Mutex. 
I'll take a look in free time. I've done some intensive testing and the overhead has been negligible.

The way I use the library is usually to count event occurrence during the process execution, e.g. how many times someone was trying to request a weird path from webserver or how many times a user data was corrupted (e.g. weird cookie or form values).

In an ideal case it would export the counters to Prometheus or Stackdriver.

If you want you can fork the lib and prepare it yourself ;-)
